apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w0hq1kbmq-go 
  janus-idp.io/tekton: w0hq1kbmq-go
  backstage.io/kubernetes-id: w0hq1kbmq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w0hq1kbmq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml